// <auto-generated />
using System;
using HelipadManager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelipadManager.Migrations
{
    [DbContext(typeof(ShiftDbContext))]
    [Migration("20260912221531_ConnectionsSetting")]
    partial class ConnectionsSetting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("HeliTaskStaffMember", b =>
                {
                    b.Property<int>("ExecutorsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TasksId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExecutorsId", "TasksId");

                    b.HasIndex("TasksId");

                    b.ToTable("HeliTaskStaffMembers", (string)null);
                });

            modelBuilder.Entity("HelicopterShift", b =>
                {
                    b.Property<int>("HelicoptersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HelicoptersId", "ShiftsId");

                    b.HasIndex("ShiftsId");

                    b.ToTable("ShiftHelicopters", (string)null);
                });

            modelBuilder.Entity("HelipadManager.HeliTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desctiprion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HelicopterId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HelicopterId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("HelipadManager.Helicopter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlightStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TailNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Usability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Helicopters");
                });

            modelBuilder.Entity("HelipadManager.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("HelipadManager.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManager")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("HeliTaskStaffMember", b =>
                {
                    b.HasOne("HelipadManager.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("ExecutorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelipadManager.HeliTask", null)
                        .WithMany()
                        .HasForeignKey("TasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelicopterShift", b =>
                {
                    b.HasOne("HelipadManager.Helicopter", null)
                        .WithMany()
                        .HasForeignKey("HelicoptersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelipadManager.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelipadManager.HeliTask", b =>
                {
                    b.HasOne("HelipadManager.Helicopter", null)
                        .WithMany("Tasks")
                        .HasForeignKey("HelicopterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelipadManager.Shift", null)
                        .WithMany("ManagerTasks")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelipadManager.StaffMember", b =>
                {
                    b.HasOne("HelipadManager.Shift", null)
                        .WithMany("StaffMembers")
                        .HasForeignKey("ShiftId");
                });

            modelBuilder.Entity("HelipadManager.Helicopter", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("HelipadManager.Shift", b =>
                {
                    b.Navigation("ManagerTasks");

                    b.Navigation("StaffMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
