// <auto-generated />
using System;
using HelipadManager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelipadManager.Migrations
{
    [DbContext(typeof(ShiftDbContext))]
    [Migration("20260908210911_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("HelicopterShift", b =>
                {
                    b.Property<int>("HelicoptersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HelicoptersId", "ShiftsId");

                    b.HasIndex("ShiftsId");

                    b.ToTable("HelicopterShift");
                });

            modelBuilder.Entity("HelipadManager.HeliTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Desctiprion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HeliId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HelicopterId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HelicopterId");

                    b.HasIndex("ShiftId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("HelipadManager.Helicopter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlightStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TailNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Usability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Helicopters");
                });

            modelBuilder.Entity("HelipadManager.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("HelipadManager.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArmyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeliTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManager")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubTaskId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HeliTaskId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("SubTaskId");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("HelipadManager.SubTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeliTaskId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HeliTaskId");

                    b.ToTable("SubTasks");
                });

            modelBuilder.Entity("HelicopterShift", b =>
                {
                    b.HasOne("HelipadManager.Helicopter", null)
                        .WithMany()
                        .HasForeignKey("HelicoptersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelipadManager.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelipadManager.HeliTask", b =>
                {
                    b.HasOne("HelipadManager.Helicopter", null)
                        .WithMany("Tasks")
                        .HasForeignKey("HelicopterId");

                    b.HasOne("HelipadManager.Shift", null)
                        .WithMany("ManagerTasks")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelipadManager.StaffMember", b =>
                {
                    b.HasOne("HelipadManager.HeliTask", null)
                        .WithMany("Executors")
                        .HasForeignKey("HeliTaskId");

                    b.HasOne("HelipadManager.Shift", null)
                        .WithMany("StaffMembers")
                        .HasForeignKey("ShiftId");

                    b.HasOne("HelipadManager.SubTask", null)
                        .WithMany("Executors")
                        .HasForeignKey("SubTaskId");
                });

            modelBuilder.Entity("HelipadManager.SubTask", b =>
                {
                    b.HasOne("HelipadManager.HeliTask", null)
                        .WithMany("SubTasks")
                        .HasForeignKey("HeliTaskId");
                });

            modelBuilder.Entity("HelipadManager.HeliTask", b =>
                {
                    b.Navigation("Executors");

                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("HelipadManager.Helicopter", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("HelipadManager.Shift", b =>
                {
                    b.Navigation("ManagerTasks");

                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("HelipadManager.SubTask", b =>
                {
                    b.Navigation("Executors");
                });
#pragma warning restore 612, 618
        }
    }
}
